[package]
name = "guh-chess"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
egui_extras = { version = "0.32.0", features = ["all_loaders"] }
image = { version = "0.25.6", features = ["png"] }
rand = "0.9.2"
